<?php 
//variaveis e seus repectivos significados

$AGRO='3';
$INFO='1';
$ADMIN='9';
$M_AMBIENTE='5';
$INT_AGRO='4';
$CURSOS='2';
$PERIODO='6';
$RCC='0';
$ACC='7';
$TCC='8';
$CC='10';

//MULTA

$VM='103';//VISUALIZAR
$CM='104';//FORMULARIO
$LM='105';//LIMPAR
$RLM='106';//REGISTRAR LIMPAR
$RM='107';//REGISTRAR

// EMPRESTIMO

$LCE='108';//VISUALIZAR
$CE='109';//CRIAR
$RE='110';//REGISTRAR

//DEVOLUCAO

$CD='111';//FOLHA
$RCD='112';//PAGINA DE REGISTRO PHP


//RESERVA

$CR='113';//CRIAR
$VR='114';//VISUALIZAR
$VRI='11';//VISUALIZAR por item
$RCR='36';

//CADASTRO ADCIONAIS

$CL='12';//LIVRO
$RCL='13';//REGISTRAR LIVRO
$CU='41';//USUARIO
$RCU='42';//REGISTRAR USUÁRIO
$CMD='14';//MIDIA
$RCMD='15';//REGISTRAR MIDIA
$CF='16';//FOLHETO
$RCF='17';//REGISTRAR FOLHETO
$CT='18';//TEXTOS ANUARIOS
$RCT='19';//REGISTRAR TEXTOS ANUARIOS
$CA='20';//AUTOR
$RCA='21';//REGISTRAR AUTOR
$CI='22';//IDOMA
$RCI='23';//REGISTRAR IDOMA
$CED='24';//EDITORA
$RCED='25';//REGISTRAR EDITORA
$CTM='26';//TIPO MIDIA
$RCTM='27';//REGISTRAR TIPO MIDIA
$CTA='28';//TIPO AQUISICAO
$RCTA='29';//REGISTRAR TIPO AQUISICAO

//ALTERAR DADOS

$ADU='30';//USUARIO
$VADU='72';//USUARIO

$ADIT='31';//ITEM ACERVO
$VADIT='31';//VISUALIZAR ITEM ACERVO

$ADID='31';//ITEM ACERVO
$VADID='31';//VISUALIZAR ITEM ACERVO

$ADA='32';//AUTORES
$VADA='58';//VISUALIZA AuTORES

$ADE='66';//EDITORA
$VADE='67';//VISUALIZAR EDITORA

$ADI='68';//IDIOMA
$VADI='34';//VISUALIZAR IDIOMA

$ADTM='70';//TIPO MIDIA
$VADTM='35';//VISUALIZAR MIDIA

$ADM='59';//MIDIA
$VADM='60';//VISUALIZAR MIDIA

$ADF='73';//FOLHETO
$VADF='62';//VISUALIZAR FOLHETO

$ADT='43';//TEXTOS / ANUÁRIOS / RELATORIOS
$VADT='63';//TEXTOS / ANUÁRIOS / RELATORIOS

$P='57';//PESQUISAR

$ADL='40';//LIVRO
$VADL='44';//LIVRO
//---------complementos
$REMP='80';//RENOVAÇAO EMPRESTIMO
$REV='81';//cadastra EMPRESTIMO DE RESERVA
$RGM='102';
$RGAM= '120';
$ALT='130';
?>